fetch security group id dynamically

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,12 +1,7 @@
 name: CI/CD Workflow
 
 on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+  workflow_dispatch: {}
 
 
 jobs:
@@ -82,6 +77,35 @@ jobs:
           fi
           echo "EC2_INSTANCE=$EC2_INSTANCE" >> $GITHUB_ENV
 
+      - name: Get Security Group ID
+        run: |
+          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups \
+          --region ${{ secrets.AWS_REGION }} \
+          --filters "Name=group-name,Values=meridian-retail-server-sg" \
+          --query 'SecurityGroups[0].GroupId' \
+          --output text)
+
+          if [ -z "$SECURITY_GROUP_ID" ] || [ "$SECURITY_GROUP_ID" = "None" ]; then
+            echo "Security group not found"
+            exit 1
+          fi
+
+          echo "Security Group ID: $SECURITY_GROUP_ID"
+          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> "$GITHUB_ENV"
+
+      - name: Get GitHub runner IP
+        id: runner-ip
+        run: |
+          echo "ip=$(curl -s https://ipv4.icanhazip.com)" >> "$GITHUB_OUTPUT"
+
+      - name: Allow GitHub runner SSH
+        run: |
+          aws ec2 authorize-security-group-ingress \
+          --group-id ${{ env.SECURITY_GROUP_ID }} \
+          --protocol tcp \
+          --port 22 \
+          --cidr ${{ steps.runner-ip.outputs.ip }}/32
+
       - name: Copy docker compose file to EC2
         uses: appleboy/scp-action@v1
         with:
@@ -97,9 +121,9 @@ jobs:
           host: ${{ env.EC2_INSTANCE }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
           envs: ECR_REGISTRY
           script: |
+            set -e
             cd /home/${{ secrets.EC2_USERNAME }}/app || exit 1
             # Create .env
             cat << EOF > .env
@@ -123,3 +147,14 @@ jobs:
             docker compose -f docker-compose.prod.yml up -d --remove-orphans
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+
+      
+      - name: Remove GitHub runner SSH access
+        if: always()
+        run: |
+          aws ec2 revoke-security-group-ingress \
+          --group-id ${{ env.SECURITY_GROUP_ID }} \
+          --protocol tcp \
+          --port 22 \
+          --cidr ${{ steps.runner-ip.outputs.ip }}/32
+
diff --git a/.github/workflows/provision.yml b/.github/workflows/provision.yml
--- a/.github/workflows/provision.yml
+++ b/.github/workflows/provision.yml
@@ -35,6 +35,22 @@ jobs:
           fi
           echo "EC2_INSTANCE=$EC2_INSTANCE" >> "$GITHUB_ENV"
 
+      - name: Get Security Group ID
+        run: |
+          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups \
+          --region ${{ secrets.AWS_REGION }} \
+          --filters "Name=group-name,Values=meridian-retail-server-sg" \
+          --query 'SecurityGroups[0].GroupId' \
+          --output text)
+
+          if [ -z "$SECURITY_GROUP_ID" ] || [ "$SECURITY_GROUP_ID" = "None" ]; then
+            echo "Security group not found"
+            exit 1
+          fi
+
+          echo "Security Group ID: $SECURITY_GROUP_ID"
+          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> "$GITHUB_ENV"
+
       - name: Get GitHub runner IP
         id: runner-ip
         run: |
@@ -43,7 +59,7 @@ jobs:
       - name: Allow GitHub runner SSH
         run: |
           aws ec2 authorize-security-group-ingress \
-          --group-id ${{ secrets.SECURITY_GROUP_ID }} \
+          --group-id ${{ env.SECURITY_GROUP_ID }} \
           --protocol tcp \
           --port 22 \
           --cidr ${{ steps.runner-ip.outputs.ip }}/32
@@ -72,8 +88,8 @@ jobs:
           host: ${{ env.EC2_INSTANCE }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
           script: |
+            set -e
             cd /home/${{ secrets.EC2_USERNAME }}/app/scripts
             chmod +x *.sh
             sudo ./server_setup.sh
@@ -84,8 +100,8 @@ jobs:
           host: ${{ env.EC2_INSTANCE }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
           script: |
+            set -e
             cd /home/${{ secrets.EC2_USERNAME }}/app/nginx
             sudo cp meridian-http.conf /etc/nginx/sites-available/meridian-http.conf
             sudo ln -sf /etc/nginx/sites-available/meridian-http.conf /etc/nginx/sites-enabled/meridian-http.conf
@@ -99,9 +115,9 @@ jobs:
           host: ${{ env.EC2_INSTANCE }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
           envs: DOMAIN
           script: |
+            set -e
             sudo certbot --nginx \
               -d "$DOMAIN" \
               -d "www.$DOMAIN" \
@@ -118,7 +134,7 @@ jobs:
         if: always()
         run: |
           aws ec2 revoke-security-group-ingress \
-          --group-id ${{ secrets.SECURITY_GROUP_ID }} \
+          --group-id ${{ env.SECURITY_GROUP_ID }} \
           --protocol tcp \
           --port 22 \
-          --cidr ${{ steps.ip.outputs.ip }}/32
+          --cidr ${{ steps.runner-ip.outputs.ip }}/32
